import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import PDFDocument from "pdfkit";

function splitParagraphs(text: string) {
  return text
    .split(/\n{2,}/)
    .map(part => part.trim())
    .filter(Boolean);
}

export async function buildDocxBuffer(title: string, body: string): Promise<Buffer> {
  const children = [
    new Paragraph({
      text: title,
      heading: HeadingLevel.HEADING_1,
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: "Generated by Norvar — review applied changes before signing.",
          italics: true,
          size: 20,
          color: "666666",
        }),
      ],
    }),
    ...splitParagraphs(body).flatMap(part => {
      const lines = part.split("\n");
      return lines.map(line =>
        new Paragraph({
          children: [new TextRun({ text: line, size: 22 })],
          spacing: { after: 120 },
        }),
      );
    }),
  ];

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  return Packer.toBuffer(doc);
}

export async function buildPdfBuffer(title: string, body: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 54, size: "LETTER" });
    const chunks: Buffer[] = [];

    doc.on("data", chunk => chunks.push(chunk as Buffer));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(16).font("Helvetica-Bold").text(title, { align: "left" });
    doc.moveDown(0.4);
    doc.fontSize(9).font("Helvetica-Oblique").fillColor("#666666")
      .text("Generated by Norvar — review applied changes before signing.");
    doc.moveDown(1);
    doc.fillColor("#000000").fontSize(10).font("Helvetica").text(body, {
      align: "left",
      lineGap: 3,
    });
    doc.end();
  });
}
