"""Global regulatory framework catalog for norvar_ingest_global.py."""

GLOBAL_REGULATIONS = [

    # ══════════════════════════════════════════════════════════════════════════
    # PRIVACY — EUROPEAN UNION
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "General Data Protection Regulation (GDPR)",
        "abbr": "GDPR",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2018,
        "url": "https://gdpr-info.eu/",
        "fallback_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679",
        "notes": "Core EU data protection regulation. Lawful basis, data subject rights, breach notification, cross-border transfers.",
    },
    {
        "name": "GDPR — Recitals (Full Text)",
        "abbr": "GDPR Recitals",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2018,
        "url": "https://gdpr-info.eu/recitals/",
        "notes": "GDPR interpretive recitals — essential for understanding legislative intent.",
    },
    {
        "name": "EU ePrivacy Directive (Cookie Law)",
        "abbr": "ePrivacy",
        "domain": "privacy",
        "subdomain": "tracking_analytics",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2009,
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32009L0136",
        "notes": "Governs cookies, tracking, and electronic communications. Critical for analytics and advertising tech.",
    },
    {
        "name": "EU Digital Markets Act (DMA) — Data Provisions",
        "abbr": "DMA",
        "domain": "privacy",
        "subdomain": "tracking_analytics",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2022,
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R1925",
        "notes": "Data portability, interoperability, and tracking restrictions on gatekeepers.",
    },
    {
        "name": "EU Digital Services Act (DSA) — Content and Data",
        "abbr": "DSA",
        "domain": "privacy",
        "subdomain": "tracking_analytics",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2022,
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R2065",
        "notes": "Transparency in recommender systems, advertising, and content moderation for online platforms.",
    },
    {
        "name": "EDPB Guidelines on Biometric Data (Article 9 GDPR)",
        "abbr": "EDPB Biometrics",
        "domain": "privacy",
        "subdomain": "biometrics",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2022,
        "url": "https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-32019-processing-personal-data-through-video_en",
        "notes": "EDPB guidance on biometric data processing including facial recognition and fingerprints.",
    },
    {
        "name": "EDPB Guidelines on Consent under GDPR",
        "abbr": "EDPB Consent",
        "domain": "privacy",
        "subdomain": "consent",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2020,
        "url": "https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-052020-consent-under-regulation-2016679_en",
        "notes": "Definitive guidance on valid consent mechanisms under GDPR.",
    },
    {
        "name": "EDPB Guidelines on Data Transfers (SCCs and BCRs)",
        "abbr": "EDPB Transfers",
        "domain": "privacy",
        "subdomain": "cross_border_transfers",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2021,
        "url": "https://www.edpb.europa.eu/our-work-tools/our-documents/recommendations/recommendations-012020-measures-supplement-transfer_en",
        "notes": "Post-Schrems II guidance on supplementary measures for international data transfers.",
    },
    {
        "name": "EU Standard Contractual Clauses (SCCs 2021)",
        "abbr": "SCCs 2021",
        "domain": "privacy",
        "subdomain": "cross_border_transfers",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2021,
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32021D0914",
        "notes": "Updated SCCs for controller-processor and processor-processor transfers.",
    },
    {
        "name": "EU-US Data Privacy Framework (DPF)",
        "abbr": "EU-US DPF",
        "domain": "privacy",
        "subdomain": "cross_border_transfers",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2023,
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32023D1795",
        "fallback_url": "https://commission.europa.eu/law/law-topic/data-protection/international-dimension-data-protection/eu-us-data-transfers_en",
        "notes": "Adequacy decision for EU-US data transfers. Replaces Privacy Shield.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # PRIVACY — UNITED KINGDOM
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "UK General Data Protection Regulation (UK GDPR)",
        "abbr": "UK GDPR",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "uk",
        "status": "enacted",
        "year": 2021,
        "url": "https://www.legislation.gov.uk/uksi/2019/419/contents",
        "fallback_url": "https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/",
        "notes": "UK post-Brexit data protection framework. Closely mirrors EU GDPR with UK-specific modifications.",
    },
    {
        "name": "UK Data Protection Act 2018",
        "abbr": "UK DPA 2018",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "uk",
        "status": "enacted",
        "year": 2018,
        "url": "https://www.legislation.gov.uk/ukpga/2018/12/contents",
        "notes": "Supplements UK GDPR, including law enforcement and intelligence processing provisions.",
    },
    {
        "name": "UK ICO Guidance on Biometric Data",
        "abbr": "ICO Biometrics",
        "domain": "privacy",
        "subdomain": "biometrics",
        "jurisdiction": "uk",
        "status": "enacted",
        "year": 2023,
        "url": "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/lawful-basis/special-category-data/what-is-special-category-data/",
        "notes": "ICO guidance on biometric data as special category data under UK GDPR.",
    },
    {
        "name": "UK ICO Guidance on Cookies and Tracking",
        "abbr": "ICO Cookies",
        "domain": "privacy",
        "subdomain": "tracking_analytics",
        "jurisdiction": "uk",
        "status": "enacted",
        "year": 2023,
        "url": "https://ico.org.uk/for-organisations/direct-marketing-and-privacy-and-electronic-communications/guide-to-pecr/cookies-and-similar-technologies/",
        "notes": "UK PECR and cookie consent requirements for analytics and advertising.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # PRIVACY — CANADA
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "Personal Information Protection and Electronic Documents Act (PIPEDA)",
        "abbr": "PIPEDA",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "canada",
        "status": "enacted",
        "year": 2000,
        "url": "https://laws-lois.justice.gc.ca/eng/acts/P-8.6/FullText.html",
        "notes": "Federal Canadian privacy law for commercial activities.",
    },
    {
        "name": "Quebec Law 25 — Act Respecting the Protection of Personal Information in the Private Sector",
        "abbr": "Quebec Law 25",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "canada",
        "status": "enacted",
        "year": 2021,
        "url": "https://www.legisquebec.gouv.qc.ca/en/document/cs/P-39.1",
        "notes": "Quebec's modernised privacy law — stricter than PIPEDA, closest Canadian equivalent to GDPR.",
    },
    {
        "name": "Canada Bill C-27 — Consumer Privacy Protection Act (CPPA)",
        "abbr": "CPPA",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "canada",
        "status": "advancing",
        "year": 2022,
        "url": "https://www.parl.ca/DocumentViewer/en/44-1/bill/C-27/first-reading",
        "notes": "Proposed federal replacement for PIPEDA. Includes AI system transparency obligations.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # PRIVACY — BRAZIL
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "Brazil Lei Geral de Proteção de Dados (LGPD)",
        "abbr": "LGPD",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "latam",
        "status": "enacted",
        "year": 2020,
        "url": "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm",
        "fallback_url": "https://iapp.org/resources/article/brazil-lgpd-english-translation/",
        "notes": "Brazil's comprehensive data protection law. Similar structure to GDPR. Enforced by ANPD.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # PRIVACY — ASIA PACIFIC
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "Singapore Personal Data Protection Act (PDPA) 2012 (amended 2021)",
        "abbr": "PDPA",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "apac",
        "status": "enacted",
        "year": 2021,
        "url": "https://www.pdpc.gov.sg/Overview-of-PDPA/The-Legislation/Personal-Data-Protection-Act",
        "fallback_url": "https://sso.agc.gov.sg/Act/PDPA2012",
        "notes": "Singapore's data protection law. Includes mandatory breach notification and data portability.",
    },
    {
        "name": "Australia Privacy Act 1988 (amended)",
        "abbr": "AU Privacy Act",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "apac",
        "status": "enacted",
        "year": 2022,
        "url": "https://www.legislation.gov.au/Details/C2022C00199",
        "notes": "Australian federal privacy law. Includes Australian Privacy Principles and Notifiable Data Breaches scheme.",
    },
    {
        "name": "Japan Act on Protection of Personal Information (APPI) 2022",
        "abbr": "APPI",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "apac",
        "status": "enacted",
        "year": 2022,
        "url": "https://www.ppc.go.jp/en/legal/",
        "notes": "Japan's updated privacy law. Extraterritorial reach, breach notification, cross-border transfer restrictions.",
    },
    {
        "name": "South Korea Personal Information Protection Act (PIPA) 2023",
        "abbr": "PIPA",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "apac",
        "status": "enacted",
        "year": 2023,
        "url": "https://www.pipc.go.kr/np/cop/bbs/selectBoardArticle.do?bbsId=BS217&mCode=D010030000&nttId=9265",
        "fallback_url": "https://iapp.org/resources/article/south-korea-pipa-english-translation/",
        "notes": "South Korea's data protection law. One of the strictest globally, with high penalties.",
    },
    {
        "name": "China Personal Information Protection Law (PIPL)",
        "abbr": "PIPL",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "apac",
        "status": "enacted",
        "year": 2021,
        "url": "https://www.chinalawtranslate.com/en/pipl/",
        "fallback_url": "https://www.chinalawtranslate.com/en/personal-information-protection-law-of-the-peoples-republic-of-china/",
        "notes": "China's comprehensive privacy law. Extraterritorial reach, data localisation, cross-border transfer restrictions.",
    },
    {
        "name": "India Digital Personal Data Protection Act (DPDPA) 2023",
        "abbr": "DPDPA",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "apac",
        "status": "enacted",
        "year": 2023,
        "url": "https://www.medianama.com/2023/08/223-digital-personal-data-protection-act-2023/",
        "fallback_url": "https://www.meity.gov.in/data-protection-framework",
        "notes": "India's first comprehensive data protection law. Consent-based framework, Data Protection Board enforcement.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # PRIVACY — MIDDLE EAST & AFRICA
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "UAE Federal Data Protection Law (DPL) 2021",
        "abbr": "UAE DPL",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "mena",
        "status": "enacted",
        "year": 2021,
        "url": "https://www.nortonrosefulbright.com/en/knowledge/publications/2a8f8f8a/uae-data-protection-law",
        "fallback_url": "https://u.ae/en/information-and-services/justice-safety-and-the-law/handling-personal-data-and-privacy",
        "fallback_method": "ssl_relaxed",
        "notes": "UAE's first federal data protection law. Applies to non-government entities.",
    },
    {
        "name": "Saudi Arabia Personal Data Protection Law (PDPL) 2021",
        "abbr": "KSA PDPL",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "mena",
        "status": "enacted",
        "year": 2021,
        "url": "https://www.taylorwessing.com/en/interface/2021/saudi-arabia-personal-data-protection-law",
        "fallback_url": "https://sdaia.gov.sa/en/SDAIA/about/Documents/Personal%20Data%20Protection%20Law%20En%20V2-2.pdf",
        "fallback_method": "pdf",
        "notes": "Saudi Arabia's national data protection law. Enforced by SDAIA.",
    },
    {
        "name": "South Africa Protection of Personal Information Act (POPIA)",
        "abbr": "POPIA",
        "domain": "privacy",
        "subdomain": "data_protection",
        "jurisdiction": "mena",
        "status": "enacted",
        "year": 2021,
        "url": "https://inforegulator.org.za/popia/",
        "fallback_url": "https://www.gov.za/documents/protection-personal-information-act",
        "notes": "South Africa's data protection law. Similar to GDPR, enforced by Information Regulator.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # PRIVACY — TRACKING, ANALYTICS & ADTECH (GLOBAL)
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "FTC Guidance on Online Tracking and Cross-Context Behavioral Advertising",
        "abbr": "FTC Tracking",
        "domain": "privacy",
        "subdomain": "tracking_analytics",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2022,
        "url": "https://www.ftc.gov/legal-library/browse/cases-proceedings/commercial-surveillance-and-data-security-rulemaking",
        "notes": "FTC guidance on tracking, cross-context advertising, and dark patterns.",
    },
    {
        "name": "EDPB Guidelines on Legitimate Interest (Art. 6(1)(f) GDPR)",
        "abbr": "EDPB Leg Interest",
        "domain": "privacy",
        "subdomain": "tracking_analytics",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2024,
        "url": "https://gdpr-info.eu/art-6-gdpr/",
        "fallback_url": "https://gdpr-info.eu/issues/legitimate-interests/",
        "notes": "Guidance on when legitimate interest applies — critical for analytics and personalisation.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # AI GOVERNANCE — EUROPEAN UNION
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "EU Artificial Intelligence Act (AI Act) — Full Text",
        "abbr": "EU AI Act",
        "domain": "ai",
        "subdomain": "high_risk_ai",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2024,
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=OJ:L_202401689",
        "fallback_url": "https://artificialintelligenceact.eu/the-act/",
        "notes": "Comprehensive EU AI regulation. Risk tiers (prohibited, high-risk, limited, minimal). GPAI provisions.",
    },
    {
        "name": "EU AI Act — Annex III (High-Risk AI Systems List)",
        "abbr": "EU AI Act Annex III",
        "domain": "ai",
        "subdomain": "high_risk_ai",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2024,
        "url": "https://artificialintelligenceact.eu/annex/3/",
        "notes": "Definitive list of high-risk AI use cases: biometric ID, critical infrastructure, education, employment, essential services, law enforcement, migration, justice.",
    },
    {
        "name": "EU AI Act — Article 5 (Prohibited AI Practices)",
        "abbr": "EU AI Act Art. 5",
        "domain": "ai",
        "subdomain": "prohibited_ai",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2024,
        "url": "https://artificialintelligenceact.eu/article/5/",
        "notes": "Prohibited AI: real-time biometric surveillance, social scoring, subliminal manipulation, exploitation of vulnerabilities.",
    },
    {
        "name": "EU AI Act — General Purpose AI (GPAI) Provisions",
        "abbr": "EU AI Act GPAI",
        "domain": "ai",
        "subdomain": "generative_ai",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2024,
        "url": "https://artificialintelligenceact.eu/article/53/",
        "notes": "GPAI model obligations including transparency, copyright, and systemic risk requirements.",
    },
    {
        "name": "GDPR Article 22 — Automated Decision-Making and Profiling",
        "abbr": "GDPR Art. 22",
        "domain": "ai",
        "subdomain": "automated_decisioning",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2018,
        "url": "https://gdpr-info.eu/art-22-gdpr/",
        "notes": "Right not to be subject to solely automated decisions with significant effects. Human review requirement.",
    },
    {
        "name": "EDPB Guidelines on Automated Decision-Making (Art. 22 GDPR)",
        "abbr": "EDPB ADM",
        "domain": "ai",
        "subdomain": "automated_decisioning",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2018,
        "url": "https://gdpr-info.eu/art-22-gdpr/",
        "fallback_url": "https://ec.europa.eu/newsroom/article29/item-detail.cfm?item_id=612053",
        "notes": "Guidance on profiling and automated decisions including safeguards and right to explanation.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # AI GOVERNANCE — UNITED STATES (FEDERAL)
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "Executive Order 14110 — Safe, Secure, and Trustworthy AI (Biden)",
        "abbr": "EO 14110",
        "domain": "ai",
        "subdomain": "ai_governance",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2023,
        "url": "https://www.federalregister.gov/documents/2023/11/01/2023-24283/safe-secure-and-trustworthy-development-and-use-of-artificial-intelligence",
        "fallback_url": "https://www.whitehouse.gov/briefing-room/presidential-actions/2023/10/30/executive-order-on-the-safe-secure-and-trustworthy-development-and-use-of-artificial-intelligence/",
        "notes": "Biden AI EO. Covers safety, security, privacy, equity, consumer protection, and international AI governance.",
    },
    {
        "name": "Executive Order 14179 — Removing Barriers to American Leadership in AI (Trump)",
        "abbr": "EO 14179",
        "domain": "ai",
        "subdomain": "ai_governance",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2025,
        "url": "https://www.whitehouse.gov/presidential-actions/2025/01/removing-barriers-to-american-leadership-in-artificial-intelligence/",
        "notes": "Revoked Biden EO 14110. Prioritises AI innovation over regulation. Affects federal AI risk frameworks.",
    },
    {
        "name": "NIST AI Risk Management Framework (AI RMF 1.0)",
        "abbr": "NIST AI RMF",
        "domain": "ai",
        "subdomain": "ai_governance",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2023,
        "url": "https://airc.nist.gov/RMF",
        "fallback_url": "https://nvlpubs.nist.gov/nistpubs/ai/nist.ai.100-1.pdf",
        "notes": "Voluntary US AI risk management framework. GOVERN, MAP, MEASURE, MANAGE functions.",
    },
    {
        "name": "NIST AI RMF — Generative AI Profile (NIST AI 600-1)",
        "abbr": "NIST GenAI",
        "domain": "ai",
        "subdomain": "generative_ai",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2024,
        "url": "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf",
        "notes": "NIST profile for managing risks of generative AI including hallucination, bias, and data provenance.",
    },
    {
        "name": "Executive Order 13960 — Promoting the Use of Trustworthy AI in Government",
        "abbr": "EO 13960",
        "domain": "ai",
        "subdomain": "ai_governance",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2020,
        "url": "https://www.federalregister.gov/documents/2020/12/08/2020-27065/promoting-the-use-of-trustworthy-artificial-intelligence-in-the-federal-government",
        "notes": "Federal AI use principles: lawful, purposeful, accurate, safe, understandable, responsible, traceable, regularly monitored.",
    },
    {
        "name": "FTC Guidance on AI and Algorithmic Systems",
        "abbr": "FTC AI",
        "domain": "ai",
        "subdomain": "ai_governance",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2023,
        "url": "https://www.ftc.gov/policy/advocacy-research/tech-at-ftc",
        "fallback_url": "https://www.ftc.gov/news-events/topics/artificial-intelligence",
        "notes": "FTC guidance on AI marketing claims, algorithmic discrimination, and deceptive AI practices.",
    },
    {
        "name": "CFPB Guidance on AI in Credit (Adverse Action Notices)",
        "abbr": "CFPB AI Credit",
        "domain": "ai",
        "subdomain": "automated_decisioning",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2023,
        "url": "https://www.consumerfinance.gov/about-us/newsroom/cfpb-issue-spotlight-analyzes-artificial-intelligence-chatbots-in-banking/",
        "notes": "CFPB on explainability requirements for AI-based credit decisions under ECOA.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # AI GOVERNANCE — BIOMETRICS (GLOBAL)
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "EDPB Guidelines on Facial Recognition in Law Enforcement",
        "abbr": "EDPB Facial Recognition",
        "domain": "ai",
        "subdomain": "biometrics",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2022,
        "url": "https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-32019-processing-personal-data-through-video_en",
        "notes": "EDPB guidance on facial recognition — restrictions, proportionality, and safeguards.",
    },
    {
        "name": "NIST Face Recognition Vendor Testing (FRVT)",
        "abbr": "NIST FRVT",
        "domain": "ai",
        "subdomain": "biometrics",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2023,
        "url": "https://pages.nist.gov/frvt/html/frvt11.html",
        "notes": "NIST evaluation of facial recognition accuracy, bias, and demographic performance.",
    },
    {
        "name": "FTC Report on Commercial Surveillance and Biometric Data",
        "abbr": "FTC Biometrics 2023",
        "domain": "ai",
        "subdomain": "biometrics",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2023,
        "url": "https://www.federalregister.gov/documents/2023/08/22/2023-17704/trade-regulation-rule-on-commercial-surveillance-and-data-security",
        "fallback_url": "https://www.ftc.gov/system/files/ftc_gov/pdf/CommercialSurveillanceNPRM.pdf",
        "fallback_method": "pdf",
        "notes": "FTC commercial surveillance rulemaking including biometric data collection and use.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # AI GOVERNANCE — ROBOTICS & AUTONOMOUS SYSTEMS (GLOBAL)
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "EU AI Act — Safety Components and Robotics (Annex I)",
        "abbr": "EU AI Act Robotics",
        "domain": "ai",
        "subdomain": "robotics",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2024,
        "url": "https://artificialintelligenceact.eu/annex/1/",
        "notes": "EU AI Act provisions applicable to AI-enabled machinery and safety components including robotics.",
    },
    {
        "name": "EU Machinery Regulation 2023/1230 — AI and Robotics",
        "abbr": "EU Machinery Reg",
        "domain": "ai",
        "subdomain": "robotics",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2023,
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32023R1230",
        "notes": "Updated EU machinery safety regulation covering AI-enabled and autonomous machinery.",
    },
    {
        "name": "NIST Robotics and Autonomous Systems Safety Framework",
        "abbr": "NIST Robotics",
        "domain": "ai",
        "subdomain": "robotics",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2022,
        "url": "https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.1270.pdf",
        "fetch_method": "pdf",
        "notes": "NIST guidance on safety, security, and trustworthiness for robotic and autonomous systems.",
    },
    {
        "name": "ISO 10218 — Robots and Robotic Devices Safety Requirements",
        "abbr": "ISO 10218",
        "domain": "ai",
        "subdomain": "robotics",
        "jurisdiction": "global",
        "status": "enacted",
        "year": 2021,
        "url": "https://www.iso.org/standard/68961.html",
        "notes": "International safety standard for industrial robots. Covers risk assessment, safeguarding, and performance.",
    },
    {
        "name": "ISO/TR 23482 — Robotics — Application of ISO 13482 (Personal Care Robots)",
        "abbr": "ISO 13482",
        "domain": "ai",
        "subdomain": "robotics",
        "jurisdiction": "global",
        "status": "enacted",
        "year": 2022,
        "url": "https://www.iso.org/standard/79399.html",
        "notes": "Safety requirements for personal care robots — physical assistant, mobile servant, person carrier types.",
    },
    {
        "name": "NHTSA Automated Driving Systems — A Vision for Safety 2.0",
        "abbr": "NHTSA ADS",
        "domain": "ai",
        "subdomain": "robotics",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2022,
        "url": "https://www.nhtsa.gov/vehicle-safety/automated-vehicles-safety",
        "fallback_url": "https://www.nhtsa.gov/document/automated-driving-systems-20-safety-principles",
        "notes": "US federal voluntary guidance for autonomous vehicle safety, testing, and deployment.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # AI GOVERNANCE — COMPUTER VISION (GLOBAL)
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "EDPB Guidelines on Video Surveillance (CCTV)",
        "abbr": "EDPB CCTV",
        "domain": "ai",
        "subdomain": "computer_vision",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2020,
        "url": "https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-32019-processing-personal-data-through-video_en",
        "notes": "EDPB guidance on CCTV and video surveillance including facial recognition in public spaces.",
    },
    {
        "name": "FTC Report on Facing the Truth About Facial Recognition",
        "abbr": "FTC Facial Recognition",
        "domain": "ai",
        "subdomain": "computer_vision",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2012,
        "url": "https://www.ftc.gov/sites/default/files/documents/reports/facing-facts-best-practices-common-uses-facial-recognition-technologies/121022facialtechrpt.pdf",
        "notes": "FTC best practices for commercial facial recognition. Foundational US guidance.",
    },
    {
        "name": "ISO/IEC 24028 — Overview of Trustworthiness in AI (Computer Vision)",
        "abbr": "ISO 24028",
        "domain": "ai",
        "subdomain": "computer_vision",
        "jurisdiction": "global",
        "status": "enacted",
        "year": 2020,
        "url": "https://www.iso.org/standard/77608.html",
        "notes": "International standard covering trustworthiness in AI systems including computer vision applications.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # AI GOVERNANCE — INTERNATIONAL FRAMEWORKS
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "OECD Principles on AI",
        "abbr": "OECD AI",
        "domain": "ai",
        "subdomain": "ai_governance",
        "jurisdiction": "global",
        "status": "enacted",
        "year": 2023,
        "url": "https://oecd.ai/en/ai-principles",
        "notes": "OECD AI principles: inclusive growth, human rights, transparency, robustness, accountability.",
    },
    {
        "name": "UNESCO Recommendation on the Ethics of AI",
        "abbr": "UNESCO AI Ethics",
        "domain": "ai",
        "subdomain": "ai_governance",
        "jurisdiction": "global",
        "status": "enacted",
        "year": 2021,
        "url": "https://www.unesco.org/en/artificial-intelligence/recommendation-ethics",
        "fallback_url": "https://unesdoc.unesco.org/ark:/48223/pf0000380455",
        "notes": "Global framework for AI ethics — human dignity, fairness, transparency, sustainability.",
    },
    {
        "name": "G7 Hiroshima AI Process — International Code of Conduct",
        "abbr": "G7 AI Code",
        "domain": "ai",
        "subdomain": "ai_governance",
        "jurisdiction": "global",
        "status": "enacted",
        "year": 2023,
        "url": "https://digital-strategy.ec.europa.eu/en/library/hiroshima-process-international-code-conduct-advanced-ai-systems",
        "fallback_url": "https://www.meti.go.jp/press/2023/10/20231031002/20231031002-1.pdf",
        "fallback_method": "pdf",
        "notes": "G7 voluntary code of conduct for advanced AI. Risk identification, transparency, incident reporting.",
    },
    {
        "name": "UK AI Safety Institute — Evaluation Framework",
        "abbr": "UK AISI",
        "domain": "ai",
        "subdomain": "ai_governance",
        "jurisdiction": "uk",
        "status": "enacted",
        "year": 2024,
        "url": "https://www.gov.uk/government/organisations/ai-safety-institute",
        "notes": "UK AI Safety Institute evaluation methodology for frontier AI models.",
    },
    {
        "name": "Canada Directive on Automated Decision-Making",
        "abbr": "CA ADM Directive",
        "domain": "ai",
        "subdomain": "automated_decisioning",
        "jurisdiction": "canada",
        "status": "enacted",
        "year": 2021,
        "url": "https://www.tbs-sct.canada.ca/pol/doc-eng.aspx?id=32592",
        "notes": "Canadian federal directive on automated decision systems — impact assessment, transparency, human review.",
    },
    {
        "name": "Singapore Model AI Governance Framework (2nd Ed)",
        "abbr": "SG AI Gov",
        "domain": "ai",
        "subdomain": "ai_governance",
        "jurisdiction": "apac",
        "status": "enacted",
        "year": 2020,
        "url": "https://www.pdpc.gov.sg/-/media/Files/PDPC/PDF-Files/Resource-for-Organisation/AI/SGModelAIGovFramework2.pdf",
        "notes": "Singapore's practical AI governance framework — risk-proportionate approach, human-in-the-loop.",
    },
    {
        "name": "China Generative AI Regulations (Provisional)",
        "abbr": "China GenAI Regs",
        "domain": "ai",
        "subdomain": "generative_ai",
        "jurisdiction": "apac",
        "status": "enacted",
        "year": 2023,
        "url": "https://www.cac.gov.cn/2023-07/13/c_1690898327029107.htm",
        "notes": "China's regulations for generative AI services — content moderation, data security, model registration.",
    },
    {
        "name": "China Algorithm Recommendation Regulations",
        "abbr": "China Algo Regs",
        "domain": "ai",
        "subdomain": "automated_decisioning",
        "jurisdiction": "apac",
        "status": "enacted",
        "year": 2022,
        "url": "https://www.chinalawtranslate.com/en/provisions-on-the-management-of-algorithmic-recommendations-in-internet-information-services/",
        "fallback_url": "https://www.cac.gov.cn/2022-01/04/c_1642960517378922.htm",
        "fetch_method": "ssl_relaxed",
        "notes": "China's rules on algorithmic recommendation systems — transparency, user rights, non-discrimination.",
    },
    {
        "name": "ISO/IEC 42001 — AI Management System Standard",
        "abbr": "ISO 42001",
        "domain": "ai",
        "subdomain": "ai_governance",
        "jurisdiction": "global",
        "status": "enacted",
        "year": 2023,
        "url": "https://www.iso.org/standard/81230.html",
        "notes": "International AI management system standard. Certifiable framework for responsible AI governance.",
    },
    {
        "name": "ISO/IEC 23894 — AI Risk Management",
        "abbr": "ISO 23894",
        "domain": "ai",
        "subdomain": "ai_governance",
        "jurisdiction": "global",
        "status": "enacted",
        "year": 2023,
        "url": "https://www.iso.org/standard/77304.html",
        "notes": "ISO standard for AI risk management integrated with ISO 31000.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # CYBERSECURITY — EUROPEAN UNION
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "NIS2 Directive — Network and Information Security",
        "abbr": "NIS2",
        "domain": "cyber",
        "subdomain": "incident_response",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2023,
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022L2555",
        "notes": "Expanded EU cybersecurity directive. Mandatory incident reporting, supply chain security, management accountability.",
    },
    {
        "name": "DORA — Digital Operational Resilience Act",
        "abbr": "DORA",
        "domain": "cyber",
        "subdomain": "financial_cyber",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2025,
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R2554",
        "notes": "EU digital resilience for financial entities. ICT risk management, incident reporting, third-party risk, TLPT.",
    },
    {
        "name": "EU Cybersecurity Act — ENISA and Certification Framework",
        "abbr": "EU CSA",
        "domain": "cyber",
        "subdomain": "certification",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2019,
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32019R0881",
        "notes": "EU cybersecurity certification framework and ENISA mandate.",
    },
    {
        "name": "EU Cyber Resilience Act (CRA)",
        "abbr": "EU CRA",
        "domain": "cyber",
        "subdomain": "product_security",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2024,
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=OJ:L_202402847",
        "notes": "Security requirements for products with digital elements — IoT, software, connected devices.",
    },
    {
        "name": "GDPR Article 32 — Security of Processing",
        "abbr": "GDPR Art. 32",
        "domain": "cyber",
        "subdomain": "data_security",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2018,
        "url": "https://gdpr-info.eu/art-32-gdpr/",
        "notes": "Technical and organisational security measures. Encryption, pseudonymisation, confidentiality, availability.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # CYBERSECURITY — UNITED STATES (FEDERAL)
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "NIST Cybersecurity Framework 2.0 (CSF 2.0)",
        "abbr": "NIST CSF 2.0",
        "domain": "cyber",
        "subdomain": "cyber_framework",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2024,
        "url": "https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.29.pdf",
        "notes": "Updated NIST CSF. GOVERN, IDENTIFY, PROTECT, DETECT, RESPOND, RECOVER functions.",
    },
    {
        "name": "NIST SP 800-53 Rev 5 — Security and Privacy Controls",
        "abbr": "NIST 800-53",
        "domain": "cyber",
        "subdomain": "security_controls",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2020,
        "url": "https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r5.pdf",
        "notes": "Comprehensive federal security and privacy controls catalogue.",
    },
    {
        "name": "CISA Cybersecurity Performance Goals (CPGs)",
        "abbr": "CISA CPGs",
        "domain": "cyber",
        "subdomain": "cyber_framework",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2023,
        "url": "https://www.cisa.gov/cpg",
        "fallback_url": "https://www.cisa.gov/cross-sector-cybersecurity-performance-goals",
        "notes": "CISA baseline cybersecurity practices for critical infrastructure sectors.",
    },
    {
        "name": "Executive Order 14028 — Improving the Nation's Cybersecurity",
        "abbr": "EO 14028",
        "domain": "cyber",
        "subdomain": "cyber_framework",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2021,
        "url": "https://www.federalregister.gov/documents/2021/05/17/2021-10460/improving-the-nations-cybersecurity",
        "notes": "Zero trust architecture, software supply chain security, SBOMs, incident reporting for federal contractors.",
    },
    {
        "name": "SEC Cybersecurity Disclosure Rules 2023",
        "abbr": "SEC Cyber Rules",
        "domain": "cyber",
        "subdomain": "incident_response",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2023,
        "url": "https://www.sec.gov/rules/final/2023/33-11216.pdf",
        "notes": "Public company cybersecurity incident disclosure (4 business days), annual risk management reporting.",
    },
    {
        "name": "FTC Safeguards Rule (Revised 2023) — Non-Bank Financial Institutions",
        "abbr": "FTC Safeguards 2023",
        "domain": "cyber",
        "subdomain": "financial_cyber",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2023,
        "url": "https://www.ecfr.gov/current/title-16/chapter-I/subchapter-C/part-314",
        "notes": "Updated FTC Safeguards Rule for non-bank financial institutions. Encryption, access controls, incident response.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # CYBERSECURITY — INTERNATIONAL STANDARDS
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "ISO/IEC 27001:2022 — Information Security Management Systems",
        "abbr": "ISO 27001",
        "domain": "cyber",
        "subdomain": "security_management",
        "jurisdiction": "global",
        "status": "enacted",
        "year": 2022,
        "url": "https://www.iso.org/standard/27001",
        "fallback_url": "https://www.iso.org/obp/ui/#iso:std:iso-iec:27001:ed-3:v1:en",
        "notes": "Certifiable international information security management standard. 93 controls across 4 themes.",
    },
    {
        "name": "ISO/IEC 27002:2022 — Information Security Controls",
        "abbr": "ISO 27002",
        "domain": "cyber",
        "subdomain": "security_controls",
        "jurisdiction": "global",
        "status": "enacted",
        "year": 2022,
        "url": "https://www.iso.org/standard/75652.html",
        "notes": "Detailed implementation guidance for ISO 27001 controls.",
    },
    {
        "name": "ISO/IEC 27701 — Privacy Information Management (PIMS)",
        "abbr": "ISO 27701",
        "domain": "cyber",
        "subdomain": "privacy_security",
        "jurisdiction": "global",
        "status": "enacted",
        "year": 2019,
        "url": "https://www.iso.org/standard/71670.html",
        "notes": "Privacy extension to ISO 27001/27002. Maps to GDPR requirements.",
    },
    {
        "name": "SOC 2 Trust Services Criteria (AICPA TSC 2017)",
        "abbr": "SOC 2",
        "domain": "cyber",
        "subdomain": "security_audit",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2017,
        "url": "https://www.aicpa.org/resources/article/soc-2-reporting-on-an-examination-of-controls-at-a-service-organization",
        "fallback_url": "https://secureframe.com/hub/soc-2/trust-services-criteria",
        "notes": "Trust Services Criteria for security, availability, processing integrity, confidentiality, and privacy.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # CYBERSECURITY — SUPPLY CHAIN & VENDOR RISK
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "NIST SP 800-161r1 — Cybersecurity Supply Chain Risk Management",
        "abbr": "NIST C-SCRM",
        "domain": "cyber",
        "subdomain": "supply_chain",
        "jurisdiction": "us_federal",
        "status": "enacted",
        "year": 2022,
        "url": "https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-161r1.pdf",
        "notes": "Comprehensive guidance on cybersecurity supply chain risk management.",
    },
    {
        "name": "EU NIS2 — ICT Supply Chain Security Requirements",
        "abbr": "NIS2 Supply Chain",
        "domain": "cyber",
        "subdomain": "supply_chain",
        "jurisdiction": "eu",
        "status": "enacted",
        "year": 2023,
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022L2555#d1e3097-80-1",
        "notes": "NIS2 supply chain security obligations — Article 21 security measures including vendor risk.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # CYBERSECURITY — SECTOR-SPECIFIC
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "PCI DSS v4.0 — Payment Card Industry Data Security Standard",
        "abbr": "PCI DSS",
        "domain": "cyber",
        "subdomain": "financial_cyber",
        "jurisdiction": "global",
        "status": "enacted",
        "year": 2022,
        "url": "https://www.pcisecuritystandards.org/document_library/",
        "notes": "Payment card security standard. 12 requirements covering network security, access control, monitoring.",
    },
    {
        "name": "UK National Cyber Security Centre (NCSC) Cyber Essentials",
        "abbr": "NCSC Essentials",
        "domain": "cyber",
        "subdomain": "cyber_framework",
        "jurisdiction": "uk",
        "status": "enacted",
        "year": 2023,
        "url": "https://www.ncsc.gov.uk/cyberessentials/overview",
        "notes": "UK government-backed baseline cybersecurity certification scheme.",
    },
    {
        "name": "Australia Essential Eight Maturity Model",
        "abbr": "AU Essential Eight",
        "domain": "cyber",
        "subdomain": "cyber_framework",
        "jurisdiction": "apac",
        "status": "enacted",
        "year": 2023,
        "url": "https://learn.microsoft.com/en-us/compliance/anz/e8-overview",
        "fallback_url": "https://www.cyber.gov.au/acsc/view-all-content/essential-eight",
        "fallback_method": "ssl_relaxed",
        "notes": "Australian Cyber Security Centre's baseline mitigation strategies.",
    },
    {
        "name": "Singapore Cybersecurity Act 2018",
        "abbr": "SG CSA",
        "domain": "cyber",
        "subdomain": "incident_response",
        "jurisdiction": "apac",
        "status": "enacted",
        "year": 2018,
        "url": "https://sso.agc.gov.sg/Act/CA2018",
        "notes": "Singapore's cybersecurity law covering critical information infrastructure protection and incident response.",
    },
    {
        "name": "China Cybersecurity Law (CSL) 2017",
        "abbr": "China CSL",
        "domain": "cyber",
        "subdomain": "data_security",
        "jurisdiction": "apac",
        "status": "enacted",
        "year": 2017,
        "url": "https://www.newamerica.org/cybersecurity-initiative/digichina/blog/translation-cybersecurity-law-peoples-republic-china/",
        "notes": "China's cybersecurity law covering network operators, data localisation, and critical infrastructure.",
    },
    {
        "name": "China Data Security Law (DSL) 2021",
        "abbr": "China DSL",
        "domain": "cyber",
        "subdomain": "data_security",
        "jurisdiction": "apac",
        "status": "enacted",
        "year": 2021,
        "url": "https://www.chinalawtranslate.com/en/data-security-law-of-the-peoples-republic-of-china/",
        "fallback_url": "https://www.newamerica.org/cybersecurity-initiative/digichina/blog/translation-data-security-law-peoples-republic-china/",
        "notes": "China's data security law. Data classification, important data protection, cross-border data transfer.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # AI GOVERNANCE — US STATE LEVEL (ADDITIONAL)
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "California AB 2013 — AI Training Data Transparency",
        "abbr": "CA AB 2013",
        "domain": "ai",
        "subdomain": "generative_ai",
        "jurisdiction": "us_state",
        "state": "CA",
        "status": "enacted",
        "year": 2024,
        "url": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240AB2013",
        "notes": "Requires disclosure of training data used in generative AI systems deployed in California.",
    },
    {
        "name": "California SB 1047 — Safe and Secure Innovation for Frontier AI (Vetoed)",
        "abbr": "CA SB 1047",
        "domain": "ai",
        "subdomain": "ai_governance",
        "jurisdiction": "us_state",
        "state": "CA",
        "status": "vetoed",
        "year": 2024,
        "url": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240SB1047",
        "notes": "Vetoed California frontier AI safety bill. Context for ongoing state AI governance landscape.",
    },
    {
        "name": "Illinois Artificial Intelligence Video Interview Act",
        "abbr": "IL AI Video",
        "domain": "ai",
        "subdomain": "automated_decisioning",
        "jurisdiction": "us_state",
        "state": "IL",
        "status": "enacted",
        "year": 2020,
        "url": "https://www.ilga.gov/legislation/ilcs/documents/075000650K5.htm",
        "fallback_url": "https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=3995&ChapterID=68",
        "notes": "Illinois law requiring employer disclosure and consent for AI-analysed video interviews.",
    },
    {
        "name": "Washington State AI Systems Fairness Act (HB 1951)",
        "abbr": "WA AI Fairness",
        "domain": "ai",
        "subdomain": "automated_decisioning",
        "jurisdiction": "us_state",
        "state": "WA",
        "status": "enacted",
        "year": 2024,
        "url": "https://app.leg.wa.gov/billsummary?BillNumber=1951&Year=2023",
        "notes": "Washington AI fairness requirements for consequential decisions — employment, housing, credit.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # PRIVACY — TRACKING, ADTECH & ANALYTICS (US STATE)
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "California CPPA — Cybersecurity Audit Regulations",
        "abbr": "CA CPPA Cyber Audit",
        "domain": "cyber",
        "subdomain": "security_audit",
        "jurisdiction": "us_state",
        "state": "CA",
        "status": "advancing",
        "year": 2024,
        "url": "https://cppa.ca.gov/regulations/",
        "notes": "California CPPA proposed cybersecurity audit rules for high-risk businesses.",
    },
    {
        "name": "California CPPA — Risk Assessment Regulations",
        "abbr": "CA CPPA Risk",
        "domain": "privacy",
        "subdomain": "risk_assessment",
        "jurisdiction": "us_state",
        "state": "CA",
        "status": "advancing",
        "year": 2024,
        "url": "https://cppa.ca.gov/regulations/",
        "notes": "California privacy risk assessment requirements for high-risk processing activities.",
    },
]
